version: '3.7'

services:
  sw-example-app-php:
    image: library/php:8.0-fpm
    volumes:
      - ./:/app:rw

  sw-example-app-nginx:
    image: library/nginx:1.19
    ports:
      - 80:80
    volumes:
      - ./:/app:ro
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
