version: '3.7'

services:
  php:
    env_file:
      - .env
    image: library/php:8.0-fpm
    volumes:
      - ./:/app:rw

  nginx:
    image: library/nginx:1.19
    ports:
      - '8181:80'
    volumes:
      - ./:/app:ro
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro

  shopware:
    image: dockware/play:latest
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html/custom/apps/SwExampleApp:rw

  composer:
    image: composer/composer:2
    volumes:
      - ./:/app:rw
