version: '3.7'

services:
  php:
    image: library/php:8.0-fpm
    volumes:
      - ./:/app:rw

  nginx:
    image: library/nginx:1.19
    ports:
      - '8181:80'
    volumes:
      - ./:/app:ro
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro

  shopware:
    image: dockware/play:6.4.4.0
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html/custom/apps/SwExampleApp:rw

  composer:
    image: composer/composer:2
    volumes:
      - ./:/app:rw
