version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    image: library/php:8.0-fpm
    volumes:
      - ./:/app:rw
    working_dir: /app

  nginx:
    image: library/nginx:1.19
    ports:
      - '8181:80'
    volumes:
      - ./:/app:ro
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /app

  shopware:
    image: dockware/play:latest
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html/custom/apps/SwExampleApp:rw

  composer:
    image: composer/composer:2
    volumes:
      - ./:/app:rw
